# Generated by Django 5.1.3 on 2025-12-28 00:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_schedule_scheduleview'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='baseview',
            options={'default_related_name': 'views', 'ordering': ['name'], 'verbose_name': 'View', 'verbose_name_plural': 'Views'},
        ),
        migrations.AlterModelOptions(
            name='display',
            options={'default_related_name': 'displays', 'ordering': ['name'], 'verbose_name': 'Display', 'verbose_name_plural': 'Displays'},
        ),
        migrations.AlterModelOptions(
            name='htmlview',
            options={'default_related_name': 'html_views', 'ordering': ['name'], 'verbose_name': 'HTML View', 'verbose_name_plural': 'HTML Views'},
        ),
        migrations.AlterModelOptions(
            name='iframeview',
            options={'default_related_name': 'iframe_views', 'ordering': ['name'], 'verbose_name': 'Iframe View', 'verbose_name_plural': 'Iframe Views'},
        ),
        migrations.AlterModelOptions(
            name='imageview',
            options={'default_related_name': 'image_views', 'ordering': ['name'], 'verbose_name': 'Image View', 'verbose_name_plural': 'Image Views'},
        ),
        migrations.AlterModelOptions(
            name='mediafile',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='playlist',
            options={'ordering': ['name']},
        ),
        migrations.AlterModelOptions(
            name='schedule',
            options={'default_related_name': 'schedules', 'ordering': ['name'], 'verbose_name': 'Schedule', 'verbose_name_plural': 'Schedules'},
        ),
        migrations.AlterModelOptions(
            name='scheduleview',
            options={'default_related_name': 'schedule_views', 'ordering': ['name'], 'verbose_name': 'Schedule View', 'verbose_name_plural': 'Schedule Views'},
        ),
        migrations.AlterModelOptions(
            name='videoview',
            options={'default_related_name': 'video_views', 'ordering': ['name'], 'verbose_name': 'Video View', 'verbose_name_plural': 'Video Views'},
        ),
        migrations.AddField(
            model_name='scheduleview',
            name='duration_limit',
            field=models.PositiveIntegerField(blank=True, help_text='Filter schedule entries longer than x minutes', null=True, verbose_name='Duration Limit'),
        ),
        migrations.AddField(
            model_name='scheduleview',
            name='guid_filter',
            field=models.CharField(blank=True, help_text='GUID Room filter for schedule as semicolon-separated list', max_length=256, null=True, verbose_name='GUID Filter'),
        ),
    ]
