# Generated by Django 5.2.17 on 2026-09-01 21:21

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_duration_limit_add_guid_filter_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MastodonPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('hashtags', models.CharField(help_text='Semicolon-separated list of hashtags, e.g. "datenspuren;c3sd"', max_length=512, verbose_name='Hashtags')),
                ('post_data', models.JSONField(blank=True, null=True, verbose_name='Post Data')),
                ('last_fetched', models.DateTimeField(blank=True, null=True, verbose_name='Last Fetched')),
                ('last_changed', models.DateTimeField(auto_now=True, verbose_name='Last Changed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Mastodon Post',
                'verbose_name_plural': 'Mastodon Posts',
                'ordering': ['name'],
                'default_related_name': 'mastodon_posts',
            },
        ),
        migrations.CreateModel(
            name='MastodonPostView',
            fields=[
                ('baseview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.baseview')),
                ('refresh_interval', models.PositiveIntegerField(default=60, help_text='Refresh interval in seconds', verbose_name='Refresh Interval')),
                ('mastodon_post', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.mastodonpost', verbose_name='Mastodon Post')),
            ],
            options={
                'verbose_name': 'Mastodon Post View',
                'verbose_name_plural': 'Mastodon Post Views',
                'ordering': ['name'],
                'default_related_name': 'mastodon_post_views',
            },
            bases=('core.baseview',),
        ),
    ]
