# Generated by Django 5.2.17 on 2026-09-01 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mastodonpost_mastodonpostview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastodonpost',
            name='hashtags',
            field=models.CharField(help_text='Comma or semicolon-separated list of hashtags, e.g. "datenspuren;c3sd"', max_length=512, verbose_name='Hashtags'),
        ),
    ]
