# Generated by Django 5.2.17 on 2026-09-04 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mastodonpost_cache_posts'),
    ]

    operations = [
        migrations.CreateModel(
            name='RandomView',
            fields=[
                ('baseview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.baseview')),
                ('targets', models.ManyToManyField(blank=True, help_text='One of these is picked at random every time this view is shown.', related_name='random_views', to='core.baseview', verbose_name='Views')),
            ],
            options={
                'verbose_name': 'Random View',
                'verbose_name_plural': 'Random Views',
                'ordering': ['name'],
                'default_related_name': 'random_views_set',
            },
            bases=('core.baseview',),
        ),
    ]
