# Generated by Django 5.2.17 on 2026-09-04 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_randomview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='schedules/', verbose_name='File'),
        ),
    ]
