# Generated by Django 5.2.17 on 2026-09-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_alter_schedule_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='last_reloaded_at',
            field=models.DateTimeField(editable=False, null=True, verbose_name='Last Reloaded At'),
        ),
    ]
