# Generated by Django 5.2.17 on 2026-09-04 22:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_display_last_reloaded_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='display',
            name='last_reload_delayed',
            field=models.BooleanField(default=False, editable=False),
        ),
    ]
