# Generated by Django 5.2.17 on 2026-09-08 17:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_display_last_reload_delayed'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('latitude', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Latitude')),
                ('longitude', models.DecimalField(decimal_places=5, max_digits=8, verbose_name='Longitude')),
                ('forecast_data', models.JSONField(blank=True, default=list, verbose_name='Forecast Data')),
                ('last_fetched', models.DateTimeField(blank=True, null=True, verbose_name='Last Fetched')),
                ('last_changed', models.DateTimeField(auto_now=True, verbose_name='Last Changed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'Weather Location',
                'verbose_name_plural': 'Weather Locations',
                'ordering': ['name'],
                'default_related_name': 'weather_locations',
            },
        ),
        migrations.CreateModel(
            name='WeatherView',
            fields=[
                ('baseview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.baseview')),
                ('refresh_interval', models.PositiveIntegerField(default=1800, help_text='Refresh interval in seconds', verbose_name='Refresh Interval')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.weatherlocation', verbose_name='Weather Location')),
            ],
            options={
                'verbose_name': 'Weather View',
                'verbose_name_plural': 'Weather Views',
                'ordering': ['name'],
                'default_related_name': 'weather_views',
            },
            bases=('core.baseview',),
        ),
    ]
