# Generated by Django 5.2.17 on 2026-09-11 16:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_weatherlocation_weatherview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DVBStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_id', models.CharField(max_length=32, unique=True, verbose_name='Stop ID')),
                ('name', models.CharField(max_length=128, verbose_name='Name')),
                ('city', models.CharField(blank=True, max_length=128, verbose_name='City')),
                ('last_changed', models.DateTimeField(auto_now=True, verbose_name='Last Changed')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
            ],
            options={
                'verbose_name': 'DVB Stop',
                'verbose_name_plural': 'DVB Stops',
                'ordering': ['city', 'name'],
                'default_related_name': 'dvb_stops',
            },
        ),
        migrations.CreateModel(
            name='DVBView',
            fields=[
                ('baseview_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='core.baseview')),
                ('departures_per_stop', models.PositiveIntegerField(default=7, help_text='How many upcoming departures to show for each stop.', verbose_name='Departures per Stop')),
                ('refresh_interval', models.PositiveIntegerField(default=60, help_text='Refresh interval in seconds', verbose_name='Refresh Interval')),
                ('stops', models.ManyToManyField(blank=True, related_name='dvb_views', to='core.dvbstop', verbose_name='Stops')),
            ],
            options={
                'verbose_name': 'DVB View',
                'verbose_name_plural': 'DVB Views',
                'ordering': ['name'],
                'default_related_name': 'dvb_views',
            },
            bases=('core.baseview',),
        ),
    ]
