# Generated by Django 5.2.17 on 2026-09-11 17:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_dvbstop_dvbview'),
    ]

    operations = [
        migrations.CreateModel(
            name='DVBViewStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excluded_lines', models.CharField(blank=True, help_text='Hide these lines at this stop, semicolon-separated (e.g. "3;7") - useful when a line also stops nearby and is shown at that other stop instead. Leave blank to show every line.', max_length=256, verbose_name='Excluded Lines')),
                ('stop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='view_entries', to='core.dvbstop')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stop_entries', to='core.dvbview')),
            ],
            options={
                'verbose_name': 'DVB View Stop',
                'verbose_name_plural': 'DVB View Stops',
            },
        ),
        # Django won't AlterField an M2M straight into a through= one - drop the plain M2M's
        # auto-generated join table and add it back pointing at the new through model instead.
        migrations.RemoveField(
            model_name='dvbview',
            name='stops',
        ),
        migrations.AddField(
            model_name='dvbview',
            name='stops',
            field=models.ManyToManyField(blank=True, related_name='dvb_views', through='core.DVBViewStop', to='core.dvbstop', verbose_name='Stops'),
        ),
        migrations.AddConstraint(
            model_name='dvbviewstop',
            constraint=models.UniqueConstraint(fields=('view', 'stop'), name='dvb_view_stop_unique'),
        ),
    ]
