# Generated by Django 5.2.17 on 2026-09-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_dvbviewstop_alter_dvbview_stops_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvbviewstop',
            name='excluded_destinations',
            field=models.CharField(blank=True, help_text='Hide vehicles with these final destinations at this stop, semicolon-separated (e.g. "Btf. Trachenberge") - useful for a depot-only run nobody can actually board. Leave blank to show every destination.', max_length=256, verbose_name='Excluded Destinations'),
        ),
    ]
