# Generated by Django 5.2.17 on 2026-09-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_dvbviewstop_excluded_destinations'),
    ]

    operations = [
        migrations.AddField(
            model_name='dvbviewstop',
            name='walking_minutes',
            field=models.PositiveIntegerField(default=0, help_text='Minutes it takes to walk to this stop. Departures leaving sooner than this are hidden, since nobody could reach the stop in time. Leave at 0 to show every departure.', verbose_name='Walking Minutes'),
        ),
    ]
