# Generated by Django 5.2.17 on 2026-09-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_dvbviewstop_walking_minutes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mastodonpost',
            name='recent_window',
            field=models.PositiveIntegerField(default=780, help_text='A post younger than this is shown exclusively. (seconds)', verbose_name='Recent Window'),
        ),
    ]
